#
# Makefile for the sensors drivers.
#

# Each configuration option enables a list of files.
ifdef CONFIG_SENSORS_FPRINT_FPC_PLATFORM_1145
obj-$(CONFIG_SENSORS_FINGERPRINT)		+= fpc1145/
endif

ifdef CONFIG_SENSORS_FPRINT_FPC_PLATFORM_1291
obj-$(CONFIG_SENSORS_FINGERPRINT)		+= fpc1291/
endif
